---
title: "project"
output: html_document
---
#setup and preprocessing
```{r}
#https://www.kaggle.com/usgs/earthquake-database
library(tidyverse)
quakes <- read.csv('./DATA/earthquakes.csv')

#remove columns with NA
quakes <- quakes%>%
  select(1:6, 9:10, 17:21)

quakes <- quakes%>%
  mutate(Date=as.Date(Date, "%m/%d/%Y"))
head(quakes)

```


#helper functions
```{r}



##LOCATION
get_quakes_by_lat_lng<- function(lat, lng){
  l <- quakes%>%
    filter(Latitude==lat & Longitude==lng)
  return (l)
}
get_quakes_between_lat_lng_vals <- function(lat_minor, lat_major, lng_minor, lng_major){
  return( quakes%>%
            filter(Latitude>= lat_minor & Latitude<= lat_major &
                     Longitude>= lng_minor & Longitude<= lng_major))
}

get_quakes_near_by_lat_lng <- function(lat, lng, dist_percentage){
  amt_lat<-90*2*dist_percentage
  amt_lng<- 180*2*dist_percentage
  
  lat_minor<- lat-amt_lat
  lat_major<- lat+amt_lat
  
  lng_minor <- lng-amt_lng
  lng_major <- lng+amt_lng
  
  return( get_quakes_between_lat_lng_vals(lat_minor, lat_major, lng_minor, lng_major))
  
}


##MAGNITUDE
get_quakes_by_mag <- function(mag){
  return(quakes %>%
           filter(Magnitude==mag))
}

get_quakes_by_mag_window <- function(mag1, mag2){
  return(quakes %>%
           filter(Magnitude>=mag1 & Magnitude<= mag2))
}

get_quakes_by_min_mag <- function(mag){
  return(quakes%>%
           filter(Magnitude>= mag))
}

##DATES
get_quakes_by_min_date <- function(date){
  return(quakes%>%
           filter(as.Date(Date)>=date))
}

get_quakes_by_max_date <- function(date){
  date<- as.Date(date)
  return(quakes%>%
           filter(as.Date(Date)<=date))
}

get_quakes_between_dates <- function(date1, date2){
  return (quakes %>%
    filter(as.Date(Date)>= date1 & as.Date(Date)<= date2 ))
}

get_quakes_on_date <- function(date){
    return(quakes%>%
           filter(as.Date(Date)<=date))
}

#DEPTH
get_quakes_by_min_depth <- function(depth){
  return(quakes%>%
           filter(Depth>=depth))
}
get_quakes_by_max_depth <- function(depth){
  return(quakes%>%
           filter(Depth<=depth))
}

get_quakes_near_by_lat_lng(-20.57900, -140.9720, 0.6)
#get_quakes_by_max_depth(70.0)

#get_quakes_on_date("1965-01-05")
#get_quakes_by_min_date("1965-01-05")
#get_quakes_by_min_mag(3)
#get_quakes_by_mag(6)
#get_quakes_by_lat_lng(19.246, 145.616)
```

#Map functions
```{r}
#install.packages( c("cowplot", "googleway", "ggplot2", "ggrepel","ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
#install.packages("devtools")
#install.packages("sf")
#devtools::install_github("ropenscilabs/rnaturalearth")
# load packages
library(ggplot2)

library(leaflet)

max_num_points<- 650
quakes
# Show first 20 rows from the `quakes` dataset
leaflet(data = quakes[1:max_num_points,]) %>% addTiles() %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Magnitude), label = ~as.character(Date))

```

```{r}
library(shiny)
library(tidyverse)
library(ggplot2)
library(leaflet)
quakes <- read.csv('./DATA/earthquakes.csv')

#remove columns with NA
quakes <- quakes%>%
  select(1:6, 9:10, 17:21)

quakes <- quakes%>%
  mutate(Date=as.Date(Date, "%m/%d/%Y"))

ui <- fluidPage(
  titlePanel("BC Liquor Store prices"),
  sidebarLayout(
    sidebarPanel(
      
      
      sliderInput("priceInput", "Price", 0, 100, c(25, 40), pre = "$"),
      radioButtons("typeInput", "Product type",
                   choices = unique(bcl$Type),
                   selected = "WINE"),
      selectInput("countryInput", "Country",
                  choices = unique(bcl$Country))
    ),
    mainPanel(
    
      plotOutput("coolplot"),
      br(), br(),
      tableOutput("results")
    )
  )
)

server <- function(input, output) {
  
  
  output$coolplot <- renderPlot({
    filtered <-
      bcl %>%
      filter(Price >= input$priceInput[1],
             Price <= input$priceInput[2],
             Type == input$typeInput,
             Country == input$countryInput
      )
leaflet(data = quakes[1:max_num_points,]) %>% addTiles() %>%
  addMarkers(~Longitude, ~Latitude, popup = ~as.character(Magnitude), label = ~as.character(Date))
  })
  
  output$results <- renderTable({
    filtered <-
      bcl %>%
      filter(Price >= input$priceInput[1],
             Price <= input$priceInput[2],
             Type == input$typeInput,
             Country == input$countryInput
      )
    filtered
  })
  
  
}

shinyApp(ui = ui, server = server)

```
#Example
```{r}
#SETUP
library(shiny)
library(tidyverse)
library(leaflet)

quakes <- read.csv('./DATA/earthquakes.csv')
quakes <- quakes%>%
  select(1:6, 9:10, 17:21)
quakes <- quakes%>%
  mutate(Date=as.Date(Date, "%m/%d/%Y"))
head(quakes)

max_num_points<- 650

#FUNCTIONS
get_quakes_by_mag_window <- function(mag1, mag2){
  return(quakes %>%
           filter(Magnitude>=mag1 ,Magnitude <= mag2))
}
get_quakes_between_dates <- function(date1, date2){
  return (quakes %>%
    filter(as.Date(Date)>= date1 & as.Date(Date)<= date2 ))
}
get_quakes_between_lat_lng_vals <- function(lat_minor, lat_major, lng_minor, lng_major){
  return( quakes%>%
            filter(Latitude>= lat_minor & Latitude<= lat_major &
                     Longitude>= lng_minor & Longitude<= lng_major))
}


##SHINY FRONT END
ui <- fluidPage(
  titlePanel("Significant Earthquakes by Intensity and Location (1965-2016)"),
  sidebarLayout(
    sidebarPanel(
      
      
      sliderInput("magInput", h3("Magnitude"), 5.0, 10.0, c(5, 7), step=0.1),
      sliderInput("maxNumberToDisplay", h3("How Many Earthquakes?"),
                       min = 0, max = 650, value = 50),
      dateRangeInput("dates", h3("Date range:"),
                 start  = "1965-01-01",
                 end    = "2010-12-31",
                 min    = "1965-01-01",
                 max    = "2010-12-31",
                 format = "m/d/yyyy",
                 separator = " - "),
  sliderInput("latInput", h3("Latitiude Range"), -90, 90, c(-45, 45)),
  sliderInput("lngInput", h3("Longitude Range"), -180, 180, c(-90, 90)),
  
  checkboxGroupInput("checkGroup", 
                              h3("Select Filters"), 
                              choices = list("Magnitude" = "mag", 
                                             "Dates" = "dates",
                                             "Latitude and Longitude"="latlong"),
                              selected = c("mag", "dates", "latlong")),
    ),
    mainPanel(
    
      leafletOutput("mymap")

    )
  )
)

#SHINY BACK END
server <- function(input, output) {
  output$mymap <- renderLeaflet({
    selected_filters <- input$checkGroup

    
    if("mag" %in% selected_filters){
      quakes <- get_quakes_by_mag_window(input$magInput[1],input$magInput[2])
    }
    
    if("dates" %in% selected_filters){
          quakes <- get_quakes_between_dates(input$dates[1], input$dates[2])

    }
    
    if("latlong" %in% selected_filters){
       quakes <- get_quakes_between_lat_lng_vals(input$latInput[1], input$latInput[2],
                                              input$lngInput[1], input$lngInput[2])
    }
    
    max_num_points <- input$maxNumberToDisplay
    
    leaflet(data = quakes[1:max_num_points,]) %>% addTiles() %>%
    addMarkers(~Longitude, ~Latitude, popup = ~as.character(Magnitude), label = ~as.character(Date))

    
  })

  
  
  
}

shinyApp(ui = ui, server = server)
```
